#!/bin/bash


function red()
{
	echo -e "\e[31m $1 \e[0m"
}

function green()
{
	echo -e "\e[32m $1 \e[0m"
}

function yello()
{
	echo -e "\e[33m $1 \e[0m"
}

function blue()
{
	echo -e "\e[34m $1 \e[0m"
}

function blinkred()
{
	echo -e "\e[31m\e[05m $1 \e[0m"
}

function blinkgreen()
{
	echo -e "\e[32m\e[05m $1 \e[0m"
}

function blinkyello()
{
	echo -e "\e[33m\e[05m $1 \e[0m"
}

function blinkblue()
{
	echo -e "\e[34m\e[05m $1 \e[0m"
}


#格式
#echo -e "\033[字背景颜色;字体颜色m字符串\033[控制码"
#echo -e "\e[字背景颜色;字体颜色m字符串\e[控制码"

#字体背景颜色
#40:黑 
#41:深红 
#42:绿 
#43:黄色 
#44:蓝色 
#45:紫色 
#46:深绿 
#47:白色
#
#字体颜色
#30:黑 
#31:红 
#32:绿 
#33:黄 
#34:蓝色 
#35:紫色 
#36:深绿 
#37:白色 
#
#控制码
#\33[0m 关闭所有属性 
#\33[01m 设置高亮度 
#\33[04m 下划线 
#\33[05m 闪烁 
#\33[07m 反显 
#\33[08m 消隐 
#\33[30m -- \33[37m 设置前景色 
#\33[40m -- \33[47m 设置背景色 
#\33[nA 光标上移n行 
#\33[nB 光标下移n行 
#\33[nC 光标右移n行 
#\33[nD 光标左移n行 
#\33[y;xH设置光标位置 
#\33[2J 清屏 
#\33[K 清除从光标到行尾的内容 
#\33[s 保存光标位置 
#\33[u 恢复光标位置 
#\33[?25l 隐藏光标 
#\33[?25h 显示光标
#

